name: Build Resume PDF

on:
    push:
        branches: 
          - main
          - feat/ci_cd

jobs:
    build_pdf:
        runs-on: ubuntu-latest
        steps:
          - name: "Check out repository code"
            uses: actions/checkout@v4

          - name: Set up TeX Live
            uses: zauguin/install-texlive@v4
            with:
              packages: >
                context luatex latex
          
          - name: Setup Pandoc
            uses: pandoc/actions/setup@v1
          
          - name: "Run Pandoc to Generate Tex Files"
            run: |
              for f in _includes/input_documents/*.md; do
                FILE_NAME=`basename $f | sed 's/.md//g'`;
                echo $FILE_NAME.pdf; 
                echo pandoc $f --standalone \
                --template pandoc-builder-scripts/styles/green_template.tex \
                --variable papersize=A4 \
                --output external_documents/output/$FILE_NAME.tex; \
                pandoc $f --standalone \
                --template pandoc-builder-scripts/styles/green_template.tex \
                --variable papersize=A4 \
                --output external_documents/output/$FILE_NAME.tex; \
              done
              
          - name: "Run ConTeXt to Generate PDF"
            run: | 
              for f in external_documents/output/*tex; do
                echo mtxrun --path=external_documents/output \
                --result=$FILE_NAME.pdf \
                --script context $FILE_NAME.tex > external_documents/output/context_$FILE_NAME.log 2>&1; \
                mtxrun --path=external_documents/output \
                --result=$FILE_NAME.pdf \
                --script context $FILE_NAME.tex > external_documents/output/context_$FILE_NAME.log 2>&1; \
              done
          
          - name: Push Artifact
            uses: actions/upload-artifact@v4
            with:
              name: pdf-test 
              path: external_documents/ 
              retention-days: 1

          - name: Push Error
            if: failure()
            uses: actions/upload-artifact@v4
            with:
                name: failure-logs
                path: |
                  /home/runner/texlive/texmf-var/web2c/
